### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Mahlamaki** [yogajones/learning-diary#1]
Hi!

What a nice idea for a database application!

I was able to:
- test your application locally with the instructions you provided in README
- create a user
- log in and out
- make an entry, edit and delete it
- create a learning journey

I was also able to:
- make a user without a password
-make a user without a username and password

Maybe update these functions so there is a min and max limit for the inputs?

There were proper error messages when incorrect password or username where typed. Nice! 
Suggestion: maybe consider "back" buttons, so the user doesn't have to use the one in their browser. Not a major issue though!

Code was easy to read and nicely split in to folders. Tables looked nice and fitting for the purpose.

I bet you will do many upgrades to the UI, so I don't see any reason why I should comment on that too much.  That being said, maybe consider adding a welcome/homepage, so user understands what the app is about. 

Also: it would be cool, if user could add a picture (like page of a notebook) to an entry! 

Keep up the good work!

**Comment by yogajones** [comment]
Hi,

I'm glad to hear you managed to test the Lifelong Learning Diary locally with the instructions provided.

I have now added code to validate usernames and passwords. Error (and non-error) messages are now displayed as flash messages on the page where they were generated, and the user is no longer kicked out of the page (unless they are trying to access a page they have no right to).

I also created the foundation for a user-specific homepage. Everything is now behind login, except login itself and registration.

I got really excited about the possibility to add a picture of a notebook page to an entry, thanks for bringing that up! I can easily envision this feature: the entry could be scanned directly from the user's notebook. This would certainly have its benefits and is certainly something worth considering in the future, but definitely out of scope for now.

Many thanks for your valuable feedback!
